### PR TITLE
Visualization of merge sort and internationalization

### PR DESCRIPTION
**Pull request by DocSkellington**
Hello,

First of all, thank you very much for this tool! It's very nice to use... And you published it at a perfect timing, as I needed something like that for my job. So, thanks a lot!

I implemented a way to visualize the merge sort algorithm. Instead of trying to compute all the moves at once, I chose to progress step by step. That is, at the start, the implementation memorizes that the full array must be split. The first time `next_step()` is called, that split is performed and we memorized that, in the future, we will have to, in this order: split the first half of the array further down, split the second half, and, finally, merge both sub-arrays together. By repeating this recursively, we cover the whole array.
I wrote documentation in the code that explains the main steps (and the not-obvious operations to apply).

Due to my specific needs, I also added functions that dictate whether a sorting algorithm (or a visualizer) is "enabled". If this function returns false, it does not appear in the popup. I think it's more convenient than having to move files.

Finally, I added a simple way of supporting internationalization. Instead of writing the texts in the code, they are written in a CSV file. Thanks to Godot's nice features, it is very easy to use. If you want to add a brand new text, you simply have to add a new row in the CSV file with a specific key, say `KEY`. In the code, use `tr(KEY)` to ask Godot to fetch the appropriate text, according to the user's locale.
I only added French but other people can quickly add their languages, if they need so.

If you see anything that should be changed, let me know!

Thank you again for your work!

### CODE REVIEW

**Comment by DissonantVoid** [comment]
Hey @DocSkellington. I apologies for the delay, didn't mean to keep you waiting especially with such a great PR like this! Thank you so much for your contribution, this not only solves my biggest problem with this project but also does more things that I really like, I truly appreciate the effort and am glad it helped you in any way.

Your PR is great and I would like to merge it, however it has a few issues that I think can be improved, 
mainly 2 problems:
1- I think it would be better to keep the old behavior when starting the app, where you start with a default sorter/visualizer instead of forcing the user to choose before they can see anything, I understand that your approach makes the code more clean but I think it's better to give the user a taste of what the app has to offer first before having them choose different components, also this approach introduces a bug where the user can just cancel out of the popup and then hit start with no sorter/visualizer selected, causing a crash, all in all I appreciate the cleanup, but I do prefer the old approach for ease of use.
2- I see you added localization, there nothing wrong with that, I really like it even though Godot 3.x won't let me implement my language Arabic :'(
the only issue is that there isn't really a way for the user to change the language, it would be nice to have an option for that in the options popup, this isn't that big of a deal, I can implement that later, but if you want to give that a shot I'd be very grateful, I don't know how I can be more grateful than I am right now, I've reached max gratefulness knowing that you solved the merge sort hell, but I'll try lol

there are some minor things that I can take care of like `files_tracker.gd` still checking `if curr_dir != "sorter.gd"` even though we have the new `is_enabled` thingy, and some static typing and outdated comments here and there. but that's really no big deal.
again, I can't thank you enough for your work especially the merge sort implementation, I can't believe that the solution was that simple after all the mumbo-jumbo that I tried. I can finally be in peace knowing that I have one less project to worry about thanks to you!
oh also can you please squash your commits if possible

**Comment by DocSkellington** [comment]
Hello,

Thank you for your answer! I totally agree with the issues you mentioned.

If you do not mind waiting, I can work on the issues you mentioned on April 1 (this is not a joke) as I will be quite busy until then. Sorry for making you wait!

**Comment by DissonantVoid** [comment]
that's fine I understand, take as much time as needed and thank you for your help!

**Comment by DocSkellington** [comment]
Hi @DissonantVoid!

I apologize for the delay compared to what I announced. I ended up being more busy than expected.

Here is the version of my PR with the modifications you requested! I reverted my change on the booting process. Bubble sort and the vertical line visualizers are now the default again... I also modified the default font to switch to one that should support Arabic characters. I quickly tested it (by adding a new translation column in the CSV file) and it seems to display non ASCII-characters correctly. As I am definitely not able to properly translate in your language, I did not include that test. If you do not desire the font change, let me know and I'll drop that commit.

I believe the test `if curr_dir != "sorter.gd"` is still required as, by default, `is_enabled()` returns true, meaning the base class is added to the dictionary.

I also added the option to change the language at runtime and cleaned my Git history. I must admit I did not take the time to re-read the documentation and the static typing hints.

If there is anything you would like me to change, please let me know! I currently have more free time and will be able to answer more quickly.

**Comment by DissonantVoid** [comment]
hey @DocSkellington it's all good there is no time pressure for this,

I can't thank you enough for all your work! the new font is that one thing I didn't know I needed, it's much better and more compatible than the old, the whole language system is really well done, as someone who's never done any localization before I had to go back and read the docs to understand how it all works, and now I realize how well it is all put together, I couldn't have designed it any better myself, great work!

one thing I want to mention which is the `is_enabled()` function in `sorter.gd` and `visualized.gd`, I am a bit confused about how it's supposed to work, we currently check for it in `files_tracker.gd` when adding sorters/visualizers but the function always returns `true` in all classes, and I can't think of a case where we would want to return `false` other than in the base classes `sorter.gd` and `visualizer.gd` that's why I was confused about the `if curr_dir != "sorter.gd"` part before. of course this is no big deal and things work just fine as they are, yet correct me if I'm wrong but it feels like `is_enabled()` is not really contributing anything to the rest of the app, that's why I suggest we use it to exclude the base classes unless you have another purpose in mind, but again, it's just a small thing that's I'm curious about.

other than that, I'm happily ready to merge this PR, and thanks again for your help!

**Comment by DocSkellington** [comment]
Hi!

The point of the `is_enabled()` was to allow a user to quickly disable a sorter or a visualizer without needing to rename the files. In retrospect, I agree that the way I wrote it for this pull request is not really useful. So, here are the updated commits to disable the base classes and "simplify" `files_tracker.gd`.

Again, thank **you** for your work!

**Comment by DissonantVoid** [comment]
@DocSkellington I think I've prolonged this enough,
everything looks good now and I'm very happy with all the improvements you've made,

however there is one issue that, I'm just kidding :smile: it's all good now, I'm merging this bad boy

thank you for your contribution, you're awesome!

**Pull request merged**
